### ISSUE TITLE
[Feature Request] Copying results with enter key

### ISSUE THREAD

**Issue by dv5150** [laercioskt/Wox.Plugin.GoogleTranslate#2]
Hi!

Thank you for creating this plugin, it seems this one is the only one which actually works, nevertheless it works just as I expected after being 5 years on Mac, using Alfred.

However I'm just missing the feature so much that you could copy the translated result with the enter key. 
If you could implement this, it would be wonderful.

Regards,
David

**Comment by laercioskt** [comment]
Hello David,

Than you for your feedback and request.

I just implement this feature, maybe you will need to install pyperclip with the command `pip.exe install pyperclip` but the plugin will alert if it is not installed.

I appreciate any new feedback about this feature.

Regards,
Laércio
